### ISSUE TITLE
Not Working

### ISSUE THREAD

**Issue by Alibai** [NorthernSec/VeraCracker#3]
I tried the following command in Windows 10 to brute-force a newly created Veracrypt volume (with known password) and it showed some error messages. I have Python 3.5 installed and working perfectly.

python.exe C:\Users\ADMIN\Desktop\VeraCracker\VeraCracker.py -v C:\Users\ADMIN\Desktop\VeraCracker\ASDF -p C:\Users\ADMIN\Desktop\VeraCracker\passwrd.txt -m I:

In CMD it is showing the following error messages along with popup messages displaying "Error while parsing command line" for every CMD error line

TODO: Is veracrypt installed
'query' is not recognized as an internal or external command,
operable program or batch file.
'query' is not recognized as an internal or external command, 0/16807
operable program or batch file.
'query' is not recognized as an internal or external command, 1/16807
operable program or batch file.
'query' is not recognized as an internal or external command, 2/16807
operable program or batch file.
'query' is not recognized as an internal or external command, 3/16807
operable program or batch file.
'query' is not recognized as an internal or external command, 4/16807
operable program or batch file.
'query' is not recognized as an internal or external command, 5/16807
(and so on...)

Note: 16807 is the number of password combinations in the list.

I then tried with 12 passwords and it did finish, But it didn't find the password

Is it the source code or am I doing it the wrong way?

**Comment by PidgeyL** [comment]
Hey. This is a windows specific issue, that I haven't had time to fix. This is the same issue as #1, so I'm closing this one.
