### ISSUE TITLE
2 arguments given?

### ISSUE THREAD

**Issue by girbotphone** [NorthernSec/VeraCracker#4]
Running on a linux system, I've encountered error output:

> Traceback (most recent call last):
> File "VeraCracker.py", line 135, in <module>
>    if crack(p):
> File "VeraCracker.py", line 78, in linuxCrack
>     err_message = str(out, "utf-8").strip() if out else str(err, "utf-8").strip()
> TypeError: str() takes at most 1 argument (2 given)

generated  using 

`python VeraCracker.py -v /media/USER/EXTERNALDRIVE -p PASSLIST`

My results consistent  between multiple different Linux distros and versions of VeraCrypt installed on those systems.

**Comment by PidgeyL** [comment]
Are you running it with Python3?
I'm not really maintaining the code that well anymore, but I can have a quick look

**Comment by girbotphone** [comment]
I apologize for not getting back to you sooner. Yes, silly me, I was just running it as python, not python3. Thank you.
